site_name: Bluesky
repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo07
repo_name: Requisitos-de-Software/2024.2-Grupo07

nav:
  - Início: index.md
  - Atas: 
    - Ata 1: atas/ata1.md
    - Ata 2: atas/ata2.md
  - Apresentação:
    - Entregas: 
      - Entrega 1: apresentação/entregas/entrega1.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Aplicativos Avaliados: planejamento/aplicativosAvaliados.md
      - Aplicativo Selecionado: planejamento/aplicativoSelecionado.md
      - Rich Picture: planejamento/richPicture.md
      - Metodologia: planejamento/metodologia.md
  - Verificação:
    - Etapa 1:
      - Nosso Grupo (Grupo 7): 
        - Início: verificação/etapa1/Grupo7/inicio7.md
        - Apresentação: verificação/etapa1/Grupo7/apresentação7.md
        - Cronograma: verificação/etapa1/Grupo7/cronograma7.md
        - Ferramentas: verificação/etapa1/Grupo7/ferramentas7.md
        - Aplicativos Avaliados: verificação/etapa1/Grupo7/aplicativosavaliados7.md
        - Aplicativo Selecionado: verificação/etapa1/Grupo7/aplicativoselecionado7.md
        - Rich Picture: verificação/etapa1/Grupo7/riachpicture7.md
        - Metodologia: verificação/etapa1/Grupo7/metodologia7.md
      - Grupo +1 (Grupo 8):
        - Home: verificação/etapa1/Grupo8/home8.md
        - Heatmap: verificação/etapa1/Grupo8/heatmap8.md
        - Cronograma de Atividades: verificação/etapa1/Grupo8/cronogramadeatividades8.md
        - Ferramentas: verificação/etapa1/Grupo8/ferramentas8.md
        - Aplicativos Avaliados: verificação/etapa1/Grupo8/aplicativosavaliados8.md
        - Aplicativo Selecionado: verificação/etapa1/Grupo8/aplicativoselecionado8.md


theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.sections 
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.footer
  
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  icon:
    repo: fontawesome/brands/git-alt 
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Requisitos-de-Software/2024.2-Grupo07
plugins:
  - search