site_name: Bluesky
repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo07
repo_name: Requisitos-de-Software/2024.2-Grupo07

nav:
  - Início: index.md
  - Atas: 
    - Ata 1: atas/ata1.md
  - Apresentação:
    - Entregas: 
      - Entrega 1: apresentação/entregas/entrega1.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Aplicativos Avaliados: planejamento/aplicativosAvaliados.md
      - Aplicativo Selecionado: planejamento/aplicativoSelecionado.md
      - Termo de Uso: planejamento/termodeuso.md
      - Rich Picture: planejamento/richPicture.md
      - Metodologia: planejamento/metodologia.md
  - Verificação:
    - Etapa 1:
      - Nosso Grupo (Grupo 7):
        - Início: verificação/etapa1/inicio7.md
        - Apresentação: verificação/etapa1/apresentação7.md
        - Cronograma: verificação/etapa1/cronograma7.md
        - Ferramentas: verificação/etapa1/ferramentas7.md
        - Aplicativos Avaliados: verificação/etapa1/aplicativosavaliados7.md
        - Aplicativo Selecionado: verificação/etapa1/aplicativoselecionado7.md
        - Termo de Uso: verificação/etapa1/termodeuso7.md
        - Rich Picture: verificação/etapa1/riachpicture7.md
        - Metodologia: verificação/etapa1/metodologia7.md
      - Grupo +1 (Grupo 8):
        - Início: verificação/etapa1/inicio8.md
        - Apresentação: verificação/etapa1/apresentação8.md
        - Heatmap: verificação/etapa1/heatmap8.md
        - Cronograma: verificação/etapa1/cronograma8.md
        - Ferramentas: verificação/etapa1/ferramentas8.md
        - Aplicativos Avaliados: verificação/etapa1/aplicativosavaliados8.md
        - Aplicativo Selecionado: verificação/etapa1/aplicativoselecionado8.md
        - Termo de Uso: verificação/etapa1/termodeuso8.md
        - Rich Picture: verificação/etapa1/richPicture8.md
        - Metodologia: verificação/etapa1/metodologia8.md


theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.sections 
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.footer
  
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  icon:
    repo: fontawesome/brands/git-alt 
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Requisitos-de-Software/2024.2-Grupo07
plugins:
  - search