site_name: Bluesky
repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo07
repo_name: Requisitos-de-Software/2024.2-Grupo07

nav:
  - Início: index.md
  - Atas: 
    - Ata 1: atas/ata1.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/ferramentas.md
      - Aplicativos Avaliados: planejamento/aplicativosAvaliados.md
      - Aplicativo Selecionado: planejamento/aplicativoSelecionado.md
      - Rich Picture: planejamento/richPicture.md
      - Metodologia: planejamento/metodologia.md


theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.sections 
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.footer
  
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  icon:
    repo: fontawesome/brands/git-alt 
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Requisitos-de-Software/2024.2-Grupo07
plugins:
  - search